### ISSUE TITLE
Solution is not compilable in plane vs2017 or vs2015

### ISSUE THREAD

**Issue by gdennie** [ReedCopsey/Gjallarhorn.Bindable#5]

**Comment by ReedCopsey** [comment]
@gdennie I just pushed an update that causes paket to auto-restore. That's likely why it wasn't working (at least in 2017) for you.

Try pulling the latest and building in the solution. (*I have had to build 2x for paket to restore on occasion - so if the first fails, wait a second then try again)

**Comment by gdennie** [comment]
That seemed to have done the trick. Note, I did install "Xamarin for Visual Studio" but that did not resolve the issue. Thanks.
